networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: "bitnami/redis:latest"
    # just because we're running it locally
    environment:
      - REDIS_USER=user
      - REDIS_PASSWORD=password
      - REDIS_AOF_ENABLED=no
    volumes:
      - /redis-data:/bitnami/redis/data
    ports:
      - '6379:6379'
    networks:
      - app-tier
  app:
    build: .
    environment:
      - REDIS_CONNECTION_URL=redis://user:password@redis/0
    ports:
      - '8080:8080'
    depends_on:
      - redis
    networks:
      - app-tier
