networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: "bitnami/redis:latest"
    env_file: .env
    volumes:
      - /redis-data:/bitnami/redis/data
    ports:
      - '6379:6379'
    networks:
      - app-tier
  app:
    build: .
    env_file: .env
    ports:
      - '8080:8080'
    depends_on:
      - redis
    networks:
      - app-tier
